pipeline {
    agent any
    environment {
        // Change the app package to your Docker Hub repo
        Repository = "razdahan31/flask-k8s"
        Tag_Name = "v1.${env.BUILD_NUMBER}"
        App_Package = "$Repository:$Tag_Name"
        // Change the path to your pipeline
        Pipeline_Name = "k8s-pipeline"
        GitHub_Repo = "pipelines/flask-kubernetes"
        Pipeline_Path = "$Pipeline_Name/$GitHub_Repo"
        TEST_IP = sh(script: "aws ec2 describe-instances --region eu-central-1 --filters Name=tag:platform,Values=test --query 'Reservations[].Instances[].PublicIpAddress' --output text", returnStdout: true).trim()
        PROD_IP = sh(script: "aws ec2 describe-instances --region eu-central-1 --filters Name=tag:platform,Values=production --query 'Reservations[].Instances[].PublicIpAddress' --output text", returnStdout: true).trim()
    }
    triggers {
        // Checking for commits on GitHub every minute 
        pollSCM('*/1 * * * *')
    }
    stages {
        stage('Cleanup') {
            steps {
                echo 'Performing cleanup on workspace...'
                sh 'rm -rf *'
                echo 'Performing cleanup on local Docker images...'
                sh "if docker images | grep '^${Repository} ' >/dev/null 2>&1; then docker rmi \$(docker images ${Repository} --format \"{{.Repository}}:{{.Tag}}\"); fi"
            }
        }
        stage('Build') {
            steps {
                echo 'Cloning from GitHub...'
                sh 'git clone https://github.com/Raz-Dahan/pipelines.git'
                // Change the dir to your app
                dir("/var/lib/jenkins/workspace/${Pipeline_Path}/NASA-flask/") {
                    sh "cp /var/lib/jenkins/.env ."
                    echo 'Building Docker image...'
                    sh "docker build -t ${App_Package} ."
                    echo 'Pushing to Docker Hub...'
                    sh "docker push ${App_Package}"
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Deploying and Running tests on Test instance...'
                sh "/bin/bash /var/lib/jenkins/workspace/${Pipeline_Path}/scripts/deploy.sh --test ${TEST_IP} ${App_Package}"
            }
        }
        stage('Docker Hub cleanup') {
            steps {
                echo 'Remove oldest tag if there are more than 10 on Docker Hub...'
                sh "cp /var/lib/jenkins/.env /var/lib/jenkins/workspace/${Pipeline_Path}/"
                dir("/var/lib/jenkins/workspace/${Pipeline_Path}") {
                    sh "ls -la"
                    script {
                        def envVars = readEnvVarsFromFile('.env')
                        envVars.each { key, value ->
                            env."${key}" = value
                        }
                        sh "env"
                        sh "/bin/bash DH_versioncontrol.sh ${Repository}"
                    }
                }
            }
        }
        stage('Approve') {
            steps {
                echo 'Waiting for approval...'
                // For auto-approval, add "//" before the input line.
                // For manual approval, remove "//" from the input line.
                // input 'Do you want to deploy the project on production servers?'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying on Production instance...'
                sh "/bin/bash /var/lib/jenkins/workspace/${Pipeline_Path}/scripts/deploy.sh ${PROD_IP} ${App_Package}"
            }
        }
    }
}

def readEnvVarsFromFile(filePath) {
    def props = readFile file: filePath
    return props
}
