apiVersion: apps/v1
kind: Deployment
metadata:
  name: nasa-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nasa-app
  template:
    metadata:
      labels:
        app: nasa-app
    spec:
      containers:
        - name: nasa
          image: razdahan31/nasa-app:{{ .Values.TAG }}
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: nasa-service
spec:
  selector:
    app: nasa-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-db
  template:
    metadata:
      labels:
        app: redis-db
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis-db
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
