pipeline {
    agent any
    environment {
        // Change the app package to your Docker Hub repo
        Repository = "razdahan31/nasa-app"
        Tag_Name = "v1.${env.BUILD_NUMBER}"
        App_Package = "$Repository:$Tag_Name"
        GCP_Bucket = "chart-packages"
        // Change the path to your pipeline
        Pipeline_Name = "kubernetes-pipeline"
        GitHub_Repo = "pipelines/kubernetes-pipeline"
        Pipeline_Path = "/var/lib/jenkins/workspace/$Pipeline_Name/$GitHub_Repo"
        // Change additional paths if need
    }
    triggers {
        // Checking for commits on GitHub every hour 
        pollSCM('H * * * *')
    }
    stages {
        stage('Cleanup') {
            steps {
                echo 'Performing cleanup on workspace...'
                sh 'rm -rf *'
            }
        }
        stage('Build') {
            steps {
                echo 'Cloning from GitHub...'
                sh 'git clone https://github.com/Raz-Dahan/pipelines.git'
                echo 'Building...'
                sh "bash ${Pipeline_Path}/scripts/build.sh"
            }
        }
        stage('Test') {
            steps {
                echo 'Deploying and Running tests on Test Cluster...'
                sh "bash ${Pipeline_Path}/scripts/deploy.sh --test"
            }
        }
        stage('Approve') {
            steps {
                echo 'Waiting for approval...'
                // For auto-approval, add "//" before the input line.
                // For manual approval, remove "//" from the input line.
                // input 'Do you want to deploy the project on production servers?'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying on Production Cluster...'
                sh "bash ${Pipeline_Path}/scripts/deploy.sh"
            }
        }
        stage('Monitoring') {
            steps {
                echo 'Start monitoring production...'
                sh "bash ${Pipeline_Path}/scripts/monitoring.sh"
            }
        }
        stage('Registries Handaling') {
            steps {
                echo 'Uploading chart package to GCP bucket...'
                sh "gsutil cp ${Pipeline_Path}/chart/nasa-app-1.${BUILD_NUMBER}.0.tgz  gs://${GCP_Bucket}"
                echo 'Managing Docker...'
                dir("${Pipeline_Path}/scripts/") {
                    sh "cp /var/lib/jenkins/.env ."
                    sh "bash DockerHub_VCS.sh ${Repository}"
                    sh "bash DockerImages_VCS.sh ${Repository}"
                }
            }
        }
    }
}

