- name: Setup Flask Application
  hosts: localhost
  gather_facts: true

  tasks:
    - name: Update system packages
      become: true
      yum:
        name: '*'
        state: latest
      tags: update

    - name: Change directory
      become: true
      command: cd /home/ec2-user/pipelines/flask-ansible/crypto-flask/
      tags: cd

    - name: Install Python dependencies
      become: true
      pip:
        requirements: /home/ec2-user/pipelines/flask-ansible/crypto-flask/requirements.txt
      tags: pip

    - name: Set executable permissions for playbook
      become: true
      file:
        path: /home/ec2-user/pipelines/flask-ansible/crypto-flask/app.py
        mode: ugo+rx
      tags: permissions

    - name: Copy Flask service file
      become: true
      copy:
        content: |
          [Unit]
          Description=Flask Web Application
          After=network.target

          [Service]
          User=root
          WorkingDirectory=/home/ec2-user/pipelines/flask-ansible/crypto-flask
          ExecStart=/usr/local/bin/flask run --host=0.0.0.0 --port=80
          Restart=always

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/flask.service
      notify: Restart Flask Service
      tags: service

  handlers:
    - name: Restart Flask Service
      become: true
      ansible.builtin.service:
        name: flask.service
        state: restarted

- name: Start Flask service
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Start Flask service
      become: true
      ansible.builtin.service:
        name: flask.service
        state: started
        enabled: yes
      tags: service
