pipeline {
    agent any
    environment {
        App_Package = "App_Package${env.BUILD_NUMBER}.tar.gz"
        Pipeline_Path = "flask-jenkins-pipeline/pipelines/flask-jenkins"
        S3_url = "s3://raz-flask-artifacts"
        RSA_Key = "raz-key.pem"
        TEST_IP = sh(script: "aws ec2 describe-instances --region eu-central-1 --filters Name=tag:platform,Values=test --query 'Reservations[].Instances[].PublicIpAddress' --output text", returnStdout: true).trim()
        PROD_IP = sh(script: "aws ec2 describe-instances --region eu-central-1 --filters Name=tag:platform,Values=production --query 'Reservations[].Instances[].PublicIpAddress' --output text", returnStdout: true).trim()
    }
    triggers {
        pollSCM('*/1 * * * *')
    }
    stages {
        stage('Cleanup') {
            steps {
                sh 'echo "Cleaning up on workspace..."'
                sh 'rm -rf *'
            }
        }
        stage('Build') {
            steps {
                sh 'echo "Cloning from GitHub..."'
                sh 'git clone https://github.com/Raz-Dahan/pipelines.git'
                sh 'echo "Packaging..."'
                sh 'tar -czvf ${App_Package} pipelines/flask-jenkins'
                sh 'echo "Pushing to S3..."'
                sh 'aws s3 cp ${App_Package} ${S3_url}'
                sh 'echo "Making sure that the last five build packages on S3..."'
                script {
                    def objectsNum = sh(script: 'aws s3 ls ${S3_url} --recursive | wc -l', returnStdout: true).trim().toInteger()
                    if (objectsNum > 5) {
                        def oldestObject = sh(script: 'aws s3 ls ${S3_url} --recursive 2> /dev/null | head -n 1 | awk \'{print $NF}\'', returnStdout: true).trim()
                        sh "aws s3 rm ${S3_url}/${oldestObject}"
                    }
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    sh 'echo "Copying S3 object to EC2..."'
                    sh 'ssh -o StrictHostKeyChecking=no -i /var/lib/jenkins/${RSA_Key} ec2-user@${TEST_IP} "aws s3 cp ${S3_url}/${App_Package} /home/ec2-user/${App_Package}"'
                    sh 'echo "Unpacking and start the flask..."'
                    sh """ 
                    ssh -o StrictHostKeyChecking=no -i /var/lib/jenkins/${RSA_Key} ec2-user@${TEST_IP} '
                    tar -xvf /home/ec2-user/${App_Package}
                    rm -r ${App_Package}
                    /bin/bash ./flask-jenkins/deploy.sh
                    '
                    """
                    sh 'echo "Running tests..."'
                    sh '/bin/bash "/var/lib/jenkins/workspace/${Pipeline_Path}/tests.sh"'
                }
            }
        }
        stage ('Aprove') {
            steps {
                sh 'echo "Waiting for aproval..."'
                // For auto aproval add '//' before input line, for manual aproval remove '//' from input line
                // input 'Do you want to deploy project to production?'
            }
        }
        stage('Deploy') {
            steps {
                sh 'echo "Copying S3 object to ec2..."'
                sh 'ssh -o StrictHostKeyChecking=no -i /var/lib/jenkins/${RSA_Key} ec2-user@${PROD_IP} "aws s3 cp ${S3_url}/${App_Package} /home/ec2-user/${App_Package}"'
                sh 'echo "Unpacking and start the flask..."'
                sh """ 
                ssh -o StrictHostKeyChecking=no -i /var/lib/jenkins/${RSA_Key} ec2-user@${PROD_IP} '
                tar -xvf /home/ec2-user/${App_Package}
                rm -r ${App_Package}
                /bin/bash ./flask-jenkins/deploy.sh
                '
                """
            }
        }   
    }
}
